services:
  mysql:
    container_name: 'mysql-notifications-ms'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=notifications_ms'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=P4SSW0RD'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'